version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:20.10.3-git
    resource_class: small
    steps:
      - checkout
      - run:
          name: Remove host key checking
          command: |
            mkdir -m 700 -p ~/.ssh/
            echo $'Host *\n    StrictHostKeyChecking no' > ~/.ssh/config
            chmod 644 ~/.ssh/config
      - run:
          name: Run build
          command: |
            docker --debug -H=ssh://${USER}@${HOST} build --rm -t kibana:7.9-alpine ./7.9/
      # - run:
      #     name: Run kibana
      #     command: |
      #       docker run -d --name kibana -p 5601:5601 app; sleep 10;
      #       docker logs kibana
      # - run:
      #     name: Run test
      #     command: |
      #       docker run --rm --network container:kibana blacktop/httpie GET http://localhost:5601
